apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2am
  labels:
    name: wso2am
spec:
  replicas: 1
  selector:
    name: wso2am
  template:
    metadata:
      labels:
        name: wso2am
    spec:
      containers:
      - name: wso2am
        image: wso2/am-1.9.1:1.0.0
        ports:
        - containerPort: 9443
