# Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata:
  labels:
    name: wso2mb-default
  name: wso2mb-default
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    # ports that this service should serve on
    -
      name: 'servlet-http'
      port: 9763
      targetPort: 9763
      nodePort: 32121
    -
      name: 'servlet-https'
      port: 9443
      targetPort: 9443
      nodePort: 32122
    -
      name: 'amqp'
      port: 5672
      targetPort: 5672
      nodePort: 32123
    -
      name: 'amqp-ssl'
      port: 8672
      targetPort: 8672
      nodePort: 32124
    -
      name: 'mqtt'
      port: 1883
      targetPort: 1883
      nodePort: 32125
    -
      name: 'mqtt-ssl'
      port: 8833
      targetPort: 8833
      nodePort: 32126
    -
      name: 'thrift'
      port: 7611
      targetPort: 7611
      nodePort: 32127
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wso2mb-default
