---
wso2::clustering :
    enabled : true
    local_member_host : 192.168.100.20
    local_member_port : 4000
    membership_scheme : wka
    subDomain : worker
    wka :
       members :
         -
           hostname : 192.168.100.10
           port : 4000
         -
           hostname : 192.168.100.20
           port : 4000

wso2::registry_mounts:
  WSO2_CONFIG_DB:
    path: /_system/config/es
    target_path: /_system/config/es
    readOnly: true
    registryRoot: /
    enableCache: true

  WSO2_GOV_DB:
    path: /_system/governance
    target_path: /_system/governance
    readOnly: true
    registryRoot: /
    enableCache: true

wso2::dep_sync :
    enabled : false
    auto_checkout : true
    auto_commit : false
    repository_type : svn
    svn :
       url : http://svnrepo.example.com/repos/
       user : username
       password : password
       append_tenant_id: true