apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2cep-default
  labels:
    name: wso2cep-default
spec:
  replicas: 1
  selector:
    name: wso2cep-default
  template:
    metadata:
      labels:
        name: wso2cep-default
    spec:
      containers:
      -
        name: wso2cep-default
        image: wso2/cep-4.0.0:1.0.0
        ports:
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
