apiVersion: v1
kind: Service
metadata:
  labels:
    name: wso2cep-presenter
  name: wso2cep-presenter
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    # ports that this service should serve on
    -
      name: 'servlet-http'
      port: 9763
      targetPort: 9763
      nodePort: 32001
    -
      name: 'servlet-https'
      port: 9443
      targetPort: 9443
      nodePort: 32002
    -
      name: 'thrift'
      port: 7611
      targetPort: 7611
      nodePort: 32003
    -
      name: 'thrift-ssl'
      port: 7711
      targetPort: 7711
      nodePort: 32004
    -
      name: 'thrift-cassandra'
      port: 9160
      targetPort: 9160
      nodePort: 32005
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wso2cep-presenter
