apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2cep-worker
  labels:
    name: wso2cep-worker
spec:
  replicas: 1
  selector:
    name: wso2cep-worker
  template:
    metadata:
      labels:
        name: wso2cep-worker
    spec:
      containers:
      - name: wso2cep-worker
        image: wso2/cep-worker-4.0.0:1.0.0
        ports:
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        -
          containerPort: 7611
          protocol: "TCP"
        -
          containerPort: 7711
          protocol: "TCP"