apiVersion: v1
kind: Service
metadata:
  labels:
    name: wso2cep-worker
  name: wso2cep-worker
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    -
      name: 'thrift'
      port: 7611
      targetPort: 7611
      nodePort: 32006
    -
      name: 'thrift-ssl'
      port: 7711
      targetPort: 7711
      nodePort: 32007

  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wso2cep-worker
