apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2as-manager
  labels:
    name: wso2as-manager
spec:
  replicas: 1
  selector:
    name: wso2as-manager
  template:
    metadata:
      labels:
        name: wso2as-manager
    spec:
      containers:
      - name: wso2as-manager
        image: wso2/as-manager-5.3.0:0.0.1
        env:
        -
          name: KUBERNETES_MASTER
          value: http://172.17.8.101:8080
        -
          name: KUBERNETES_NAMESPACE
          value: default
        -
          name: KUBERNETES_SERVICES
          value: 'wso2as-manager,wso2as-worker'
        ports:
        - containerPort: 9443
