apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2as-manager
  labels:
    name: wso2as-manager
spec:
  replicas: 1
  selector:
    name: wso2as-manager
  template:
    metadata:
      labels:
        name: wso2as-manager
    spec:
      containers:
      - name: wso2as-manager
        image: wso2/as-manager-5.3.0:0.0.2
        ports:
        - containerPort: 9443