apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2as-worker
  labels:
    name: wso2as-worker
spec:
  replicas: 1
  selector:
    name: wso2as-worker
  template:
    metadata:
      labels:
        name: wso2as-worker
    spec:
      containers:
      - name: wso2as-worker
        image: wso2/as-5.3.0:0.0.1
        env:
        -
          name: KUBERNETES_MASTER
          value: http://172.17.8.101:8080
        -
          name: KUBERNETES_NAMESPACE
          value: default
        -
          name: KUBERNETES_SERVICES
          value: 'wso2as-manager,wso2as-worker'
        ports:
        - containerPort: 8243
