apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2esb-manager
  labels:
    name: wso2esb-manager
spec:
  replicas: 1
  selector:
    name: wso2esb-manager
  template:
    metadata:
      labels:
        name: wso2esb-manager
    spec:
      containers:
      - name: wso2esb-manager
        image: wso2/esb-manager-4.9.0:1.0.0
#        env:
#        -
#          name: KEY_STORE_PASSWORD
#          value: wso2carbon
        ports:
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"