apiVersion: v1
kind: Service
metadata:
  labels:
    name: wso2mb-default
  name: wso2mb-default
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    # ports that this service should serve on
    -
      name: 'servlet-http'
      port: 9763
      targetPort: 9763
      nodePort: 32001
    -
      name: 'servlet-https'
      port: 9443
      targetPort: 9443
      nodePort: 32002
    -
      name: 'amqp'
      port: 5672
      targetPort: 5672
      nodePort: 32003
    -
      name: 'amqp-ssl'
      port: 8672
      targetPort: 8672
      nodePort: 32004
    -
      name: 'mqtt'
      port: 1883
      targetPort: 1883
      nodePort: 32005
    -
      name: 'mqtt-ssl'
      port: 8833
      targetPort: 8833
      nodePort: 32006
    -
      name: 'thrift'
      port: 7611
      targetPort: 7611
      nodePort: 32007
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wso2mb-default
