apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2greg-publisher
  labels:
    name: wso2greg-publisher
spec:
  replicas: 2
  selector:
    name: wso2greg-publisher
  template:
    metadata:
      labels:
        name: wso2greg-publisher
    spec:
      containers:
      - name: wso2greg-publisher
        image: wso2/greg-publisher-5.1.0:1.0.0
        ports:
        -
         containerPort: 9763
         protocol: "TCP"
        -
         containerPort: 9443
         protocol: "TCP"