apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2greg-default
  labels:
    name: wso2greg-default
spec:
  replicas: 1
  selector:
    name: wso2greg-default
  template:
    metadata:
      labels:
        name: wso2greg-default
    spec:
      containers:
      - name: wso2greg-default
        image: wso2/greg-5.1.0:1.0.0
        ports:
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"