apiVersion: v1
kind: Service
metadata:
  labels:
    name: wso2brs-worker
  name: wso2brs-worker
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    -
      name: 'servlet-http'
      port: 9763
      targetPort: 9763
      nodePort: 32003
    -
      name: 'servlet-https'
      port: 9443
      targetPort: 9443
      nodePort: 32004
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: wso2brs-worker
