apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2mb
  labels:
    name: wso2mb
spec:
  replicas: 1
  selector:
    name: wso2mb
  template:
    metadata:
      labels:
        name: wso2mb
    spec:
      containers:
      - name: wso2mb
        image: wso2/mb-3.0.0:1.0.0
        ports:
        - containerPort: 9443
