apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2as-worker
  labels:
    name: wso2as-worker
spec:
  replicas: 1
  selector:
    name: wso2as-worker
  template:
    metadata:
      labels:
        name: wso2as-worker
    spec:
      containers:
      - name: wso2as-worker
        image: wso2/as-worker-5.3.0:1.0.0
        ports:
          -
            containerPort: 9763
            protocol: "TCP"
          -
            containerPort: 9443
            protocol: "TCP"