apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2as
  labels:
    name: wso2as
spec:
  replicas: 1
  selector:
    name: wso2as
  template:
    metadata:
      labels:
        name: wso2as
    spec:
      containers:
      -
        name: wso2as
        image: wso2/as-5.3.0:1.0.0
        ports:
        -
          containerPort: 8280
          protocol: "TCP"
        -
          containerPort: 8243
          protocol: "TCP"
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
