apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2esb
  labels:
    name: wso2esb
spec:
  replicas: 1
  selector:
    name: wso2esb
  template:
    metadata:
      labels:
        name: wso2esb
    spec:
      containers:
      -
        name: wso2esb
        image: wso2/esb-4.9.0:1.0.0
        ports:
        -
          containerPort: 8280
          protocol: "TCP"
        -
          containerPort: 8243
          protocol: "TCP"
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
