# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2bps-default
  labels:
    name: wso2bps-default
spec:
  replicas: 1
  selector:
    name: wso2bps-default
  template:
    metadata:
      labels:
        name: wso2bps-default
    spec:
      containers:
      -
        name: wso2bps-default
        image: wso2bps:3.5.0
        env:
        -
          name: KUBERNETES_MASTER_SKIP_SSL_VERIFICATION
          value: "true"
#        -
#          name: KEY_STORE_PASSWORD
#          value: wso2carbon
        ports:
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
